apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlimitsrequests
  annotations:
    description: Enforce cpu memory limits
spec:
  crd:
    spec:
      names:
        kind: k8srequiredlimitsrequests
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlimitsrequests


        violation[{"msg": msg}] {
          general_violation[{"msg": msg, "field": "containers"}]
        }

        general_violation[{"msg": msg, "field": field}] {
          input.review.object.kind == "Deployment"
          container := input.review.object.spec[field][_]
          not container.resources.limits
          msg := sprintf("container <%v> has no resource limits", [container.name])
        }

        general_violation[{"msg": msg, "field": field}] {
          input.review.object.kind == "Deployment"
          container := input.review.object.spec[field][_]
          missing(container.resources.limits, "memory")
          msg := sprintf("container <%v> has no memory limit", [container.name])
        }
