apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlimitsrequests
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLimitsRequests
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sresources

        violation[{"msg": msg}] {
          provided := {c | c := input.review.object.spec.template.spec.containers[_]; not startswith(c.name, "init-")}

          mainContainers := {c | c := provided[_]; not (c.resources.limits.memory or c.resources.requests.memory or c.resources.requests.cpu)}

          count(mainContainers) > 0

          msg := sprintf("Main Containers %v should have CPU and Memory requests and Memory limits specified, but they are not.", [mainContainers])
        }

